// ui/src/app/billdata/billdata.component.ts
//
// Swiss QR Bill Generator
// Copyright (c) 2018 Manuel Bleichenbacher
// Licensed under MIT License
// https://opensource.org/licenses/MIT
//
import { Component, OnInit, NgZone } from '@angular/core';
import {
  FormControl,
  FormGroup,
  FormBuilder,
  Validators
} from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { TranslateService, LangChangeEvent } from '@ngx-translate/core';
import { Observable, Subscription, Subject } from 'rxjs';
import { QrBillService } from '../qrbill-api/qrbill.service';
import { QrBill } from '../qrbill-api/qrbill';
import { ValidationResponse } from '../qrbill-api/validation-response';
import { PreviewComponent } from '../preview/preview.component';
import { BillSingletonService } from '../bill-singleton-service/bill-singleton.service';
import { IBANFormatter } from '../input-fields/iban-formatter';
import { ReferenceNumberFormatter } from '../input-fields/ref-number-formatter';
import { AmountFormatter } from '../input-fields/amount-formatter';
import { Payments } from '../payments/payments';
import { startWith, map } from 'rxjs/operators';

@Component({
  selector: 'qrbill-data',
  templateUrl: './billdata.component.html',
  styleUrls: ['./billdata.component.css'],
  providers: [IBANFormatter, ReferenceNumberFormatter]
})
export class BillDataComponent implements OnInit {
  public bill: QrBill;
  public billForm: FormGroup;
  public isQRIBAN = false;
  public readonly refNoChanges: Subject<string> = new Subject<string>();
  public refNoSuggestions?: Observable<string[]>;
  private validatedBill?: QrBill;
  private billID?: string;
  private validationInProgress = 0;
  private previewPressed = false;

  constructor(
    private formBuilder: FormBuilder,
    private qrBillService: QrBillService,
    private dialog: MatDialog,
    private translate: TranslateService,
    billSingleton: BillSingletonService,
    public amountFormatter: AmountFormatter,
    public ibanFormatter: IBANFormatter,
    public refNumberFormatter: ReferenceNumberFormatter,
    private ngZone: NgZone
  ) {
    this.bill = billSingleton.getBill();
    this.checkAccountKind(this.bill);
    // The below validations are only for a quick feedback. The real validation is performed server-side and
    // only server-side messages are displayed.
    this.billForm = new FormGroup(
      {
        account: new FormControl(this.bill.account, {
          validators: [
            Validators.required,
            Validators.pattern('[A-Za-z0-9 ]{5,30}')
          ]
        }),
        creditor: new FormGroup({
          name: new FormControl(this.bill.creditor?.name, {
            validators: Validators.required
          }),
          street: new FormControl(this.bill.creditor?.street),
          houseNo: new FormControl(this.bill.creditor?.houseNo),
          countryCode: new FormControl(this.bill.creditor?.countryCode, {
            validators: [Validators.required, Validators.pattern('[A-Za-z]{2}')]
          }),
          postalCode: new FormControl(this.bill.creditor?.postalCode, {
            validators: Validators.required
          }),
          town: new FormControl(this.bill.creditor?.town, {
            validators: Validators.required
          })
        }),
        currency: new FormControl(this.bill.currency, {
          validators: [Validators.required, Validators.pattern('[A-Za-z]{3}')]
        }),
        amount: new FormControl(this.bill.amount, {
          validators: [Validators.min(0), Validators.max(999999999.99)]
        }),
        reference: new FormControl(this.bill.reference, {
          validators: [Validators.pattern('[A-Za-z0-9 ]{5,40}')]
        }),
        unstructuredMessage: new FormControl(this.bill.unstructuredMessage),
        billInformation: new FormControl(this.bill.billInformation),
        format: this.formBuilder.group({
          language: new FormControl(this.bill.format?.language),
          outputSize: new FormControl(this.bill.format?.outputSize),
          separatorType: new FormControl(this.bill.format?.separatorType)
        }),
        debtor: this.formBuilder.group({
          name: new FormControl(this.bill.debtor?.name),
          street: new FormControl(this.bill.debtor?.street),
          houseNo: new FormControl(this.bill.debtor?.houseNo),
          countryCode: new FormControl(this.bill.debtor?.countryCode, {
            validators: Validators.pattern('[A-Za-z]{2}')
          }),
          postalCode: new FormControl(this.bill.debtor?.postalCode),
          town: new FormControl(this.bill.debtor?.town)
        })
      },
      {
        updateOn: 'blur'
      }
    );
  }

  ngOnInit() {
    // Server-side validation on each change
    this.billForm.valueChanges.subscribe(val => {
      const bill = this.getBill(val);
      this.checkAccountKind(bill);
      this.validateServerSide(bill);
    });

    this.translate.onLangChange.subscribe((params: LangChangeEvent) => {
      this.validateServerSide(this.billForm?.value);
    });

    this.refNoSuggestions = this.refNoChanges.pipe(
      startWith(''),
      map(val => this.generateRefNos(val, this.isQRIBAN))
    );
  }

  refNoHasChanged(event: Event): void {
    this.refNoChanges.next((event.target as HTMLInputElement).value);
  }

  // Send data to server for validation
  private validateServerSide(bill: QrBill): Subscription {
    this.validationInProgress++;
    this.previewPressed = false;
    return this.qrBillService
      .validate(bill, this.translate.currentLang)
      .subscribe(response => this.updateServerSideErrors(response));
  }

  private checkAccountKind(bill: QrBill) {
    this.isQRIBAN = Payments.isQRIBAN(bill.account);
  }

  // Use the validation response to update the error messages in the UI
  updateServerSideErrors(response: ValidationResponse) {
    this.validatedBill = response.validatedBill;
    this.billID = response.billID;
    this.validationInProgress--;

    this.clearServerSideErrors(this.billForm);

    const messages = response.validationMessages;
    let controlPath = ''; // control to receive the focus
    if (messages) {
      for (const msg of messages) {
        if (msg.type === 'Error') {
          const control = this.billForm.get(msg.field ?? '');
          if (!control) {
            continue; // certain fields such as 'addressLine2' are not shown
          }
          if (controlPath === '') {
            controlPath = msg.field ?? '';
          }
          let errors = control.errors;
          if (!errors) {
            errors = {};
          }
          errors.serverSide = msg.message;
          control.setErrors(errors);
          if (msg.messageKey !== 'field_is_mandatory') {
            // Due to to dependency between 'account' and 'reference',
            // the 'reference' can become invalid without ever being touched.
            // Untouched fields do not show errors, so we mark it as touched.
            control.markAsTouched();
          }
        }
      }
    }

    // user clicked on "Preview" and is waiting for validation
    if (this.previewPressed && this.validationInProgress === 0) {
      this.previewPressed = false;
      if (messages) {
        this.focusControl(controlPath);
      } else {
        this.openPreview();
      }
    }
  }

  // Remove the errors of type "serverSide"
  private clearServerSideErrors(group: FormGroup) {
    const controls = group.controls;
    for (const controlName of Object.keys(controls)) {
      const control = controls[controlName];
      if (control instanceof FormGroup) {
        this.clearServerSideErrors(control);
      } else if (control.hasError('serverSide')) {
        let errors = control.errors;
        if (!!errors) {
          delete errors.serverSide;
          if (Object.keys(errors).length === 0) {
            errors = null;
          }
        }
        control.setErrors(errors);
      }
    }
  }

  // User has clicked "Preview" button
  preview() {
    if (!this.billForm.valid) {
      // focus invalid field
      this.focusControl(this.findFirstInvalidControl());
      return;
    }
    if (!this.billID) {
      // validate data if needed
      this.validateServerSide(this.billForm.value);
    }
    if (this.validationInProgress > 0) {
      // pending validation - postpone opening the preview
      this.previewPressed = true;
      return;
    }

    this.openPreview();
  }

  private openPreview() {
    this.dialog.open(PreviewComponent, {
      maxWidth: '100vw',
      maxHeight: '100vh',
      data: {
        validatedBill: this.validatedBill,
        billID: this.billID
      }
    });
  }

  private getBill(value: any): QrBill {
    return value as QrBill;
  }

  private focusControl(controlPath: string) {
    const pathElements = controlPath.split('.');
    const selector =
      'qrbill-data *[ng-reflect-name=' +
      pathElements.join('] *[ng-reflect-name=') +
      ']';
    this.ngZone.runOutsideAngular(() => {
      setTimeout(() => {
        const e = document.querySelector(selector);
        if (e instanceof HTMLElement) {
          e.focus();
        }
      }, 0);
    });
  }

  private generateRefNos(rawReference: string, isQRIBAN: boolean): string[] {
    const suggestions: string[] = [];
    let str = rawReference.toUpperCase();
    str = str.replace(/\W/g, '');

    if (isQRIBAN) {
      if (str.length > 0 && str.length <= 26 && str.replace(/\D/g, '') === str) {
        suggestions.push(Payments.createQRReference(str));
      }

    } else {
      if (str.startsWith('RF') && str.length > 4) {
        suggestions.push(Payments.createISO11649(str.substring(4)));
      }
      if (str.length > 0 && str.length <= 21) {
        suggestions.push(Payments.createISO11649(str));
      }
    }

    return suggestions;
  }

  private findFirstInvalidControl(
    root: FormGroup = this.billForm,
    rootPath: string = ''
  ): string {
    const controls = root.controls;
    for (const field of Object.keys(controls)) {
      const ctrl = controls[field];
      if (ctrl.invalid) {
        if (ctrl instanceof FormGroup) {
          return this.findFirstInvalidControl(ctrl, rootPath + field + '.');
        } else if (ctrl instanceof FormControl) {
          return rootPath + field;
        }
      }
    }
    return '';
  }
}

<form [formGroup]="billForm" novalidate (ngSubmit)="preview()">

  <div class="section group">

    <div class="col span_1_of_2">

      <h2 class="top-spacing" translate>account_payable_to</h2>

      <div class="form-group mat-elevation-z3">

        <div class="form-line">
          <mat-form-field class="form-field s12">
            <input qrbillInputWithFormat [inputFormatter]="ibanFormatter" placeholder="{{ 'account' | translate }}" formControlName="account" required>
            <mat-error *ngIf="billForm.hasError('serverSide', ['account'])">{{billForm.getError('serverSide', 'account')}}</mat-error>
          </mat-form-field>
        </div>

        <div formGroupName="creditor">

          <div class="form-line">
            <mat-form-field class="form-field s12">
              <input matInput placeholder="{{ 'name' | translate }}" formControlName="name" required>
              <mat-error *ngIf="billForm.hasError('serverSide', ['creditor', 'name'])">{{billForm.getError('serverSide', 'creditor.name')}}</mat-error>
            </mat-form-field>
          </div>

          <div class="form-line">
            <mat-form-field class="form-field s9">
              <input matInput placeholder="{{ 'street' | translate }}" formControlName="street">
              <mat-error *ngIf="billForm.hasError('serverSide', ['creditor', 'street'])">{{billForm.getError('serverSide', 'creditor.street')}}</mat-error>
            </mat-form-field>

            <mat-form-field class="form-field s3">
              <input matInput placeholder="{{ 'house_number' | translate }}" formControlName="houseNo">
              <mat-error *ngIf="billForm.hasError('serverSide', ['creditor', 'houseNo'])">{{billForm.getError('serverSide', 'creditor.houseNo')}}</mat-error>
            </mat-form-field>
          </div>

          <div class="form-line">
            <mat-form-field class="form-field s2">
              <input matInput placeholder="{{ 'country' | translate }}" formControlName="countryCode" required>
              <mat-error *ngIf="billForm.hasError('serverSide', ['creditor', 'countryCode'])">{{billForm.getError('serverSide', 'creditor.countryCode')}}</mat-error>
            </mat-form-field>

            <mat-form-field class="form-field s3">
              <input matInput placeholder="{{ 'postal_code' | translate }}" formControlName="postalCode" required>
              <mat-error *ngIf="billForm.hasError('serverSide', ['creditor', 'postalCode'])">{{billForm.getError('serverSide', 'creditor.postalCode')}}</mat-error>
            </mat-form-field>

            <mat-form-field class="form-field s7">
              <input matInput placeholder="{{ 'town' | translate }}" formControlName="town" required>
              <mat-error *ngIf="billForm.hasError('serverSide', ['creditor', 'town'])">{{billForm.getError('serverSide', 'creditor.town')}}</mat-error>
            </mat-form-field>
          </div>

        </div>

      </div>

      <h2 class="top-spacing" translate>bill_format</h2>

      <div class="form-group mat-elevation-z3" formGroupName="format">

        <div class="form-line">
          <mat-form-field class="form-field s4">
              <mat-select placeholder="{{ 'slip_lang' | translate}}" formControlName="language" required>
                  <mat-option value="de"><span translate>lang.de</span></mat-option>
                  <mat-option value="fr"><span translate>lang.fr</span></mat-option>
                  <mat-option value="it"><span translate>lang.it</span></mat-option>
                  <mat-option value="en"><span translate>lang.en</span></mat-option>
                </mat-select>
            <mat-error *ngIf="billForm.hasError('serverSide', ['format', 'language'])">{{billForm.getError('serverSide', 'format.language')}}</mat-error>
          </mat-form-field>
        </div>

        <div class="form-line">
          <mat-form-field class="form-field s5">
              <mat-select placeholder="{{ 'output_size' | translate}}" formControlName="outputSize" required>
                <mat-option value="qr-bill-only"><span translate>output_sizes.qr_bill_only</span></mat-option>
                <mat-option value="a4-portrait-sheet"><span translate>output_sizes.a4_portrait</span></mat-option>
                <mat-option value="qr-code-only"><span translate>output_sizes.qr_code_only</span></mat-option>
              </mat-select>
            <mat-error *ngIf="billForm.hasError('serverSide', ['format', 'outputSize'])">{{billForm.getError('serverSide', 'format.outputSize')}}</mat-error>
          </mat-form-field>

          <mat-form-field class="form-field s7">
              <mat-select placeholder="{{ 'separator_lines' | translate}}" formControlName="separatorType" required>
                <mat-option value="dashed-line-with-scissors"><span translate>separator_type.dashed_line_with_scissors</span></mat-option>
                <mat-option value="dashed-line"><span translate>separator_type.dashed_line</span></mat-option>
                <mat-option value="dotted-line-with-scissors"><span translate>separator_type.dotted_line_with_scissors</span></mat-option>
                <mat-option value="dotted-line"><span translate>separator_type.dotted_line</span></mat-option>
                <mat-option value="solid-line-with-scissors"><span translate>separator_type.solid_line_with_scissors</span></mat-option>
                <mat-option value="solid-line"><span translate>separator_type.solid_line</span></mat-option>
                <mat-option value="none"><span translate>separator_type.none</span></mat-option>
              </mat-select>
            <mat-error *ngIf="billForm.hasError('serverSide', ['format', 'separatorType'])">{{billForm.getError('serverSide', 'format.separatorType')}}</mat-error>
          </mat-form-field>
        </div>

      </div>

    </div>

    <div class="col span_1_of_2">

      <h2 class="top-spacing" translate>payment_details</h2>

      <div class="form-group mat-elevation-z3">

        <div class="form-line">
          <mat-form-field class="form-field s2">
            <mat-select placeholder="{{ 'currency' | translate}}" formControlName="currency" required>
              <mat-option value="CHF">CHF</mat-option>
              <mat-option value="EUR">EUR</mat-option>
            </mat-select>
            <mat-error *ngIf="billForm.hasError('serverSide', ['currency'])">{{billForm.getError('serverSide', 'currency')}}</mat-error>
          </mat-form-field>

          <mat-form-field class="form-field s4">
            <input qrbillInputWithFormat [inputFormatter]="amountFormatter" placeholder="{{ 'amount' | translate}}" formControlName="amount">
            <mat-error *ngIf="billForm.hasError('serverSide', ['amount'])">{{billForm.getError('serverSide', 'amount')}}</mat-error>
          </mat-form-field>
        </div>

        <div class="form-line">
          <mat-form-field class="form-field s12">
            <input qrbillInputWithFormat [inputFormatter]="refNumberFormatter" [matAutocomplete]="refNoAuto" [qrBillAutoComplete]="refNoAuto" (input)="refNoHasChanged($event)" placeholder="{{ (isQRIBAN ? 'reference_qr' : 'reference_iso') | translate }}" formControlName="reference">
            <mat-error *ngIf="billForm.hasError('serverSide', ['reference'])">{{billForm.getError('serverSide', 'reference')}}</mat-error>
          </mat-form-field>
          <mat-autocomplete #refNoAuto="matAutocomplete">
            <mat-option *ngFor="let option of refNoSuggestions | async" [value]="option"><span *ngIf="option.startsWith('RF')" class="gen">{{ option.substr(0, 4) }}</span>{{ option.startsWith('RF') ? option.substring(4) : option.substr(0, option.length - 1)}}<span *ngIf="!option.startsWith('RF')" class="gen">{{ option.substr(-1) }}</span></mat-option>
          </mat-autocomplete>
        </div>

        <div class="form-line">
          <mat-form-field class="form-field s12">
            <input matInput placeholder="{{ 'unstructured_msg' | translate }}" formControlName="unstructuredMessage">
            <mat-error *ngIf="billForm.hasError('serverSide', ['unstructuredMessage'])">{{billForm.getError('serverSide', 'unstructuredMessage')}}</mat-error>
          </mat-form-field>
        </div>

        <div class="form-line">
          <mat-form-field class="form-field s12">
            <input matInput placeholder="{{ 'bill_information' | translate }}" formControlName="billInformation">
            <mat-error *ngIf="billForm.hasError('serverSide', ['billInformation'])">{{billForm.getError('serverSide', 'billInformation')}}</mat-error>
          </mat-form-field>
        </div>

      </div>
      
      <h2 class="top-spacing" translate>payable_by</h2>

      <div class="form-group mat-elevation-z3" formGroupName="debtor">

        <div class="form-line">
          <mat-form-field class="form-field s12">
            <input matInput placeholder="{{ 'name' | translate }}" formControlName="name">
            <mat-error *ngIf="billForm.hasError('serverSide', ['debtor', 'name'])">{{billForm.getError('serverSide', 'debtor.name')}}</mat-error>
          </mat-form-field>
        </div>

        <div class="form-line">
          <mat-form-field class="form-field s9">
            <input matInput placeholder="{{ 'street' | translate }}" formControlName="street">
            <mat-error *ngIf="billForm.hasError('serverSide', ['debtor', 'street'])">{{billForm.getError('serverSide', 'debtor.street')}}</mat-error>
          </mat-form-field>

          <mat-form-field class="form-field s3">
            <input matInput placeholder="{{ 'house_number' | translate }}" formControlName="houseNo">
            <mat-error *ngIf="billForm.hasError('serverSide', ['debtor', 'houseNo'])">{{billForm.getError('serverSide', 'debtor.houseNo')}}</mat-error>
          </mat-form-field>
        </div>
  
        <div class="form-line">
          <mat-form-field class="form-field s2">
            <input matInput placeholder="{{ 'country' | translate }}" formControlName="countryCode">
            <mat-error *ngIf="billForm.hasError('serverSide', ['debtor', 'countryCode'])">{{billForm.getError('serverSide', 'debtor.countryCode')}}</mat-error>
          </mat-form-field>

          <mat-form-field class="form-field s3">
            <input matInput placeholder="{{ 'postal_code' | translate }}" formControlName="postalCode">
            <mat-error *ngIf="billForm.hasError('serverSide', ['debtor', 'postalCode'])">{{billForm.getError('serverSide', 'debtor.postalCode')}}</mat-error>
          </mat-form-field>

          <mat-form-field class="form-field s7">
            <input matInput placeholder="{{ 'town' | translate }}" formControlName="town">
            <mat-error *ngIf="billForm.hasError('serverSide', ['debtor', 'town'])">{{billForm.getError('serverSide', 'debtor.town')}}</mat-error>
          </mat-form-field>
        </div>

      </div>

    </div>

  </div>

  <div class="section group sticky-footer">

    <div class="col span_2_of_2 top-spacing">

      <div class="form-group mat-elevation-z3">
        <button mat-raised-button color="primary" type="submit"><span translate>preview_n_download</span></button>
      </div>

    </div>

  </div>

</form>

// ui/src/bill/BillData.tsx
//
// Swiss QR Bill Generator
// Copyright (c) 2022 Manuel Bleichenbacher
// Licensed under MIT License
// https://opensource.org/licenses/MIT
//

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Autocomplete, Box, Button, Card, CardContent, FormControl, FormGroup, InputLabel, MenuItem, Select, TextField, Typography } from '@mui/material';
import Grid from '@mui/material/Unstable_Grid2';
import { useTranslation } from 'react-i18next';
import { QrBill } from '../qrbill-api/qrbill';
import { validateBill } from '../qrbill-api/qrbill-api';
import { ValidationResponse } from '../qrbill-api/validation-response';
import { createISO11649, createQRReference, isQRIBAN, whiteSpaceRemoved } from './payments';
import { ibanFormatter, referenceFormatter } from './bill-helper';
import { AmountFormatter } from './amount-formatter';
import PreviewDialog from './PreviewDialog';
import FormattedTextEnh from './FormattedTextEnh';

/**
 * BillData props
 */
type BillDataProps = {
  /**
   * QR bill data to edit
   */
  bill: QrBill;

  /**
   * Function to update the bill data.
   */
  updateField: (path: string, value: any) => void;
};

/**
 * Form to edit QR bill data.
 */
const BillData: React.FC<BillDataProps> = props => {

  const { bill, updateField } = props;

  // Validation error messages currently display in the UI (pairs of field ID / message)
  const [errorMessages, setErrorMessages] = useState({} as { [fieldId: string]: string });

  // Server communication error message
  const [serverError, setServerError] = useState(undefined as string | undefined);

  const { t, i18n } = useTranslation();

  // Amount formatter (dependent on currently selected language)
  const amountFormatter = useMemo(() => new AmountFormatter(i18n.language + '-CH'), [i18n.language]);

  // Asynchronously validate bill on server-side
  const validateData = useCallback((bill: QrBill) => {
    validateBill(bill, i18n.language)
      .then((response) => { extractErrorMessages(response); setServerError(undefined); })
      .catch((reason) => setServerError(reason.message));
  }, [i18n.language]);

  // Whenever the bill changes, validate it (and on initial display)
  useEffect(() => {
    validateData(bill);
  }, [bill, validateData]);

  /**
   * Update a single field in the bill data
   * @param path path within `bill` (= field ID)
   * @param newValue new value
   */
  const updateBillField = (path: string, newValue: any) => {
    updateField(path, newValue);
  }

  /**
   * Extract the error messages from the validation response
   * @param validationResponse  validation response
   */
  const extractErrorMessages = (validationResponse: ValidationResponse) => {
    const messages: Record<string, string> = {};
    if (validationResponse.validationMessages) {
      validationResponse.validationMessages
        .filter(e => e.type === 'Error')
        .forEach(e => messages[e.field ?? 'x'] = e.message ?? 'x');
    }
    setErrorMessages(messages);
  }


  // State to open and close preview
  const [isPreviewOpen, setPreviewOpen] = useState(false);

  // bill ID required for preview
  const [billId, setBillId] = useState<string | undefined>();

  // Opens the preview dialog
  const openPreview = () => {
    setPreviewOpen(true);
    // validate the bill to get the bill ID (required for constructing the image URLs)
    validateBill(bill, i18n.language)
      .then((response) => { setBillId(response.billID); setServerError(undefined); })
      .catch((reason) => setServerError(reason.message));
  }

  // Closes the preview dialog
  const closePreview = () => {
    setPreviewOpen(false);
    setBillId(undefined);
  }

  return (
    <div>

      {serverError !== undefined ?
        <Alert severity="warning" sx={{ marginBottom: '1rem' }}>{t('connection_error', { err: serverError })}</Alert>
        : null
      }

      <form onSubmit={(event) => { event.preventDefault(); openPreview(); }}>
        <FormGroup>
          <Grid container spacing={2}>
            <Grid md={6} xs={12}>
              <Card>
                <CardContent>
                  <Grid container rowSpacing={2}>
                    <Grid>
                      <Typography gutterBottom variant="h6" component="div">{t('account_payable_to')}</Typography>
                    </Grid>
                    <Grid xs={12}>
                      <FormattedTextEnh fieldId='account' value={bill.account} labelKey='account' errorMessages={errorMessages} updateField={updateBillField} formatter={ibanFormatter} required />
                    </Grid>
                    <Grid xs={12}>
                      <FormattedTextEnh fieldId='creditor.name' value={bill.creditor?.name} labelKey='name' errorMessages={errorMessages} updateField={updateBillField} required />
                    </Grid>
                    <Grid xs={9}>
                      <FormattedTextEnh fieldId='creditor.street' value={bill.creditor?.street} labelKey='street' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={3}>
                      <FormattedTextEnh fieldId='creditor.houseNo' value={bill.creditor?.houseNo} labelKey='house_number' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={2}>
                      <FormattedTextEnh fieldId='creditor.countryCode' value={bill.creditor?.countryCode} labelKey='country' errorMessages={errorMessages} updateField={updateBillField} required />
                    </Grid>
                    <Grid xs={3}>
                      <FormattedTextEnh fieldId='creditor.postalCode' value={bill.creditor?.postalCode} labelKey='postal_code' errorMessages={errorMessages} updateField={updateBillField} required />
                    </Grid>
                    <Grid xs={7}>
                      <FormattedTextEnh fieldId='creditor.town' value={bill.creditor?.town} labelKey='town' errorMessages={errorMessages} updateField={updateBillField} required />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>
            </Grid>
            <Grid md={6} xs={12}>
              <Card>
                <CardContent>
                  <Grid container rowSpacing={2}>
                    <Grid xs={12}>
                      <Typography gutterBottom variant="h6" component="div">{t('payment_details')}</Typography>
                    </Grid>
                    <Grid xs={3}>
                      <SelectEx fieldId='currency' value={bill.currency ?? 'CHF'} labelKey='currency' itemKeys={['CHF', 'EUR']} itemsLabelKey='currencies' updateField={updateBillField} />
                    </Grid>
                    <Grid xs={4}>
                      <FormattedTextEnh fieldId='amount' value={bill.amount} isNumeric={true} labelKey='amount' errorMessages={errorMessages} updateField={updateBillField} formatter={amountFormatter} />
                    </Grid>
                    <Grid xs={12}>
                      <ReferenceAutoComplete value={bill.reference} account={bill.account} errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={12}>
                      <FormattedTextEnh fieldId='unstructuredMessage' value={bill.unstructuredMessage} labelKey='unstructured_msg' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={12}>
                      <FormattedTextEnh fieldId='billInformation' value={bill.billInformation} labelKey='bill_information' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>
            </Grid>
            <Grid md={6} xs={12}>
              <Card>
                <CardContent>
                  <Grid container rowSpacing={2}>
                    <Grid>
                      <Typography gutterBottom variant="h6" component="div">{t('payable_by')}</Typography>
                    </Grid>
                    <Grid xs={12}>
                      <FormattedTextEnh fieldId='debtor.name' value={bill.debtor?.name} labelKey='name' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={9}>
                      <FormattedTextEnh fieldId='debtor.street' value={bill.debtor?.street} labelKey='street' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={3}>
                      <FormattedTextEnh fieldId='debtor.houseNo' value={bill.debtor?.houseNo} labelKey='house_number' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={2}>
                      <FormattedTextEnh fieldId='debtor.countryCode' value={bill.debtor?.countryCode} labelKey='country' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={3}>
                      <FormattedTextEnh fieldId='debtor.postalCode' value={bill.debtor?.postalCode} labelKey='postal_code' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                    <Grid xs={7}>
                      <FormattedTextEnh fieldId='debtor.town' value={bill.debtor?.town} labelKey='town' errorMessages={errorMessages} updateField={updateBillField} />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>
            </Grid>
            <Grid md={6} xs={12}>
              <Card>
                <CardContent>
                  <Grid container rowSpacing={2}>
                    <Grid xs={12}>
                      <Typography gutterBottom variant="h6" component="div">{t('bill_format')}</Typography>
                    </Grid>
                    <Grid xs={4}>
                      <SelectEx fieldId='format.language' value={bill.format?.language ?? 'de'} labelKey='language'
                        itemKeys={['de', 'fr', 'it', 'rm', 'en']} itemsLabelKey='languages' updateField={updateBillField} />
                    </Grid>
                    <Grid xs={8}>
                    </Grid>
                    <Grid xs={5}>
                      <SelectEx fieldId='format.outputSize' value={bill.format?.outputSize ?? 'qr-bill-only'} labelKey='output_size'
                        itemKeys={['qr-bill-only', 'a4-portrait-sheet', 'qr-code-only']} itemsLabelKey='output_sizes' updateField={updateBillField} />
                    </Grid>
                    <Grid xs={7}>
                      <SelectEx fieldId='format.separatorType' value={bill.format?.separatorType ?? 'dashed-line-with-scissors'} labelKey='separator_type'
                        itemKeys={['dashed-line-with-scissors', 'dashed-line', 'dotted-line-with-scissors', 'dotted-line', 'solid-line-with-scissors', 'solid-line', 'none']}
                        itemsLabelKey='separator_types' updateField={updateBillField} />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>
            </Grid>
          </Grid>
        </FormGroup>

        <Box sx={{ position: 'sticky', bottom: '1rem', float: 'right', width: 'auto' }}>
          <Button type='submit' variant='contained' disabled={serverError !== undefined || Object.keys(errorMessages).length > 0}>{t('preview_n_download')}</Button>
        </Box>
      </form>

      <PreviewDialog isOpen={isPreviewOpen} close={closePreview} billId={billId} outputSize={bill.format?.outputSize ?? ''} />
    </div>
  );
}

type SelectExProps = {
  fieldId: string;
  value: string;
  labelKey: string;
  itemKeys: string[];
  itemsLabelKey: string;
  updateField: (path: string, value: any) => void;
};

/**
 * Select (list of options) with translated label and items
 */
const SelectEx: React.FC<SelectExProps> = props => {

  const { fieldId, value, labelKey, itemKeys, itemsLabelKey, updateField } = props;

  const { t } = useTranslation();

  return (
    <FormControl fullWidth size='small'>
      <InputLabel id={`${fieldId}-label`}>{t(labelKey)}</InputLabel>
      <Select id={fieldId} value={value}
        onChange={(e) => updateField(fieldId, e.target.value)}
        labelId={`${fieldId}-label`} label={t(labelKey)}>
        {
          itemKeys.map(item => <MenuItem key={item} value={item}>{t(`${itemsLabelKey}.${item}`)}</MenuItem>)
        }
      </Select>
    </FormControl>
  );
}

type ReferenceAutoCompleteProps = {
  /** Value to edit */
  value: any;
  /** Account number */
  account?: string;
  /** Error messages (pairs of field ID and error message) */
  errorMessages?: { [fieldId: string]: string };
  /** Functions to update the value */
  updateField: (fieldId: string, value: any) => void;
}

/**
 * Text field for reference number supporting auto completion and formatting.
 * 
 * Depending if a QR IBAN or a regular IBAN has been entered, the formatting and
 * autocompletion work differently.
 */
const ReferenceAutoComplete: React.FC<ReferenceAutoCompleteProps> = props => {

  const { value, account, errorMessages, updateField } = props;

  const formattedValue = useMemo(() => referenceFormatter.formattedValue(value), [value]);
  const [editValue, setEditValue] = useState(formattedValue);
  const [options, setOptions] = useState<readonly string[]>([]);

  const { t } = useTranslation();

  /**
   * Update the displayed options.
   * 
   * @param value current value in text field
   */
  const updateOptions = (value: string) => {
    const suggestions: string[] = [];
    let str = whiteSpaceRemoved(value.toUpperCase());

    // add check digit at the end
    if (isQRIBAN(account)) {
      if (str.length > 0 && str.length <= 26 && str.replace(/\D/g, '') === str) {
        suggestions.push(createQRReference(str));
      }

    } else {
      // replace check digits after RF
      if (str.startsWith('RF') && str.length > 4) {
        suggestions.push(createISO11649(str.substring(4)));
      }
      // prepend RFxx to value
      if (str.length > 0 && str.length <= 21) {
        suggestions.push(createISO11649(str));
      }
    }

    setOptions(suggestions);
  }

  const onBlur = () => {
    const rawValue = referenceFormatter.rawValue(editValue);
    const newFormattedValue = referenceFormatter.formattedValue(rawValue);
    setEditValue(newFormattedValue);
    if (newFormattedValue !== formattedValue)
      updateField('reference', rawValue);
  }

  return (
    <Autocomplete freeSolo disableClearable
      inputValue={editValue}
      options={options}
      onFocus={() => setEditValue(formattedValue)}
      onInputChange={(_, value) => { setEditValue(value); updateOptions(value); }}
      onBlur={onBlur}

      renderInput={params => (
        <TextField
          {...params}
          id="reference"
          error={errorMessages?.reference !== undefined} helperText={errorMessages?.reference}
          label={t(isQRIBAN(account) ? 'reference_qr' : 'reference_iso')}
          fullWidth variant="outlined" size="small" />
      )}

      renderOption={(props, option) => {
        if (option.startsWith('RF')) {
          return (
            <li {...props}>
              <span className="light">{option.substring(0, 4)}</span>
              <span>{option.substring(4)}</span>
            </li>
          )
        } else {
          return (
            <li {...props}>
              <span>{option.substring(0, option.length - 1)}</span>
              <span className="light">{option.substring(option.length - 1)}</span>
            </li>
          )
        }
      }}

      filterOptions={(x) => x}
    />
  );

}

export default BillData;
