// ui/src/app/settings/settings.component.ts
//
// Swiss QR Bill Generator
// Copyright (c) 2018 Manuel Bleichenbacher
// Licensed under MIT License
// https://opensource.org/licenses/MIT
//
import { Component } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'qrbill-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.css']
})
export class SettingsComponent {
  language: string;

  constructor(private translate: TranslateService) {
    this.language = this.translate.currentLang;
  }

  switchLanguage(lang: string) {
    this.translate.use(lang);
  }
}

// ui/src/app/Settings.tsx
//
// Swiss QR Bill Generator
// Copyright (c) 2022 Manuel Bleichenbacher
// Licensed under MIT License
// https://opensource.org/licenses/MIT
//

import { Button, Typography } from '@mui/material';
import Grid from '@mui/material/Unstable_Grid2';
import { useTranslation } from 'react-i18next';

/**
 * UI language
 */
interface Language {
  // ISO language code
  code: string;
  // Native language name (will not be translated)
  nativeName: string;
}

const languages: Language[] = [
  {
    code: 'en',
    nativeName: 'English',
  },
  {
    code: 'de',
    nativeName: 'Deutsch',
  },
];

/**
 * Settings page (for selecting the language)
 */
const Settings = () => {

  const { t, i18n } = useTranslation();

  const changeLanguage = (lang: string) => {
    void (async() => {
      await i18n.changeLanguage(lang);
    })();
  }

  return (
    <Grid container spacing={2}>
      <Grid xs={12}><Typography variant='h6'>{t('settingsLanguage')}</Typography></Grid>
      {
        languages.map((lang: Language) => (
          <Grid key={lang.code}>
            <Button variant='contained' disabled={lang.code === i18n.language} onClick={() => changeLanguage(lang.code)}>{lang.nativeName}</Button>
          </Grid>
        ))
      }
    </Grid>
  );
}

export default Settings;
